const product = [
  // jacket
  {
    cartItems:[],
    name: "Woodland Jacket",
    image:"https://images-dynamic-arcteryx.imgix.net/F22/1350x1710/Beta-Insulated-Jacket-Fluidity.jpg?auto=format%2Ccompress&fit=fill&q=75&ixlib=react-9.5.1-beta.1&w=450",
    price:140,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Calvin Klein",
    image:"https://media.istockphoto.com/id/1354251571/photo/woman-black-leather-jacket-isolated-on-white-background.jpg?b=1&s=170667a&w=0&k=20&c=a6vAf4C_HsSYvB_odR-ul-NqWX01FoNEFsK2nXthSXI=",
    price:240,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Tommy Hilfiger",
    image:"https://contents.mediadecathlon.com/p1806406/0774aca82b377d0251341e6ab1f5f857/p1806406.jpg",
    price:340,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "men",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "North face",
    image:"https://thegenuineleather.com/wp-content/uploads/2019/08/Black-leather-jacket-for-men-1.jpg",
    price:440,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "South face",
    image:"https://media.gq.com/photos/623cc30d9233ab2e539ed369/master/w_2000,h_1333,c_limit/jackets-14.jpg",
    price:60,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "East face",
    image:"https://m.media-amazon.com/images/I/91kYxNUYEVL._UX522_.jpg",
    price:70,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "women",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "West face",
    image:"https://5.imimg.com/data5/UU/YK/MY-5549871/mens-denim-jacket-500x500.jpg",
    price:80,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["s", "m", "l"],
    agegroup: "children",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "North East Face",
    image:"https://static8.depositphotos.com/1559986/1051/i/950/depositphotos_10513998-stock-photo-red-jacket.jpg",
    price:90,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "children",
    category: "Jacket",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },

  //   T-shirt
  {
    cartItems:[],
    name: "T-Shirt1",
    image:"https://cdn.pixabay.com/photo/2016/12/06/09/31/blank-1886008__340.png",
    price:140,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "T-Shirt2",
    image:"https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/de7205fd-9d54-472f-afcd-cdf85800d0b2/giannis-dri-fit-basketball-t-shirt-vsZvm1.png",
    price:240,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "T-Shirt3",
    image:"https://ih1.redbubble.net/image.4281263162.2226/ssrco,classic_tee,mens,101010:01c5ca27c6,front_alt,square_product,600x600.jpg",
    price:340,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "men",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "T-Shirt4",
    image:"https://static-01.daraz.com.np/p/1a1f858b4aa4e0ff07a03757df5629c2.png",
    price:440,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "T-Shirt5",
    image:"https://i.pinimg.com/564x/f6/96/98/f69698211c9adee48b514c85f2a03e2e.jpg",
    price:60,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "T-Shirt5",
    image:"https://www.setocanvas.com/masi/designs/creator_987/Nepalinmyheart_T_SHIRT_1-a082b0be-8557-4eff-ba81-3d08be5a7c53.jpg?v=20210326232042",
    price:70,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "women",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "T-Shirt6",
    image:"https://dealsell.com.np/public/uploads/products/thumbnail/4LzgOcEpmCf5B0cCf3zyDQUyR8npJhoxEvpGh8R4.png",
    price:80,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["s", "m", "l"],
    agegroup: "children",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "T-Shirt7",
    image:"https://cdn.shopify.com/s/files/1/0070/7032/files/tshirt-business8-min_838a2996-f195-4c1d-a4d1-034bc0a9a095.jpg?v=1597402071",
    price:90,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "children",
    category: "T-Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },

  //   Shirt
  {
    cartItems:[],
    name: "Shirt1",
    image:"https://cdn.shopify.com/s/files/1/1414/2498/products/TencelShirt_DeepLagoonnew_1_1024x1024.jpg?v=1663407953",
    price:140,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Shirt2",
    image:"https://cdn.shopify.com/s/files/1/0752/6435/products/IMG_0009_aba64f90-e74a-416b-92a7-46bd7aaa1e0e.jpg?v=1662624158",
    price:240,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Shirt3",
    image:"https://assets.myntassets.com/dpr_1.5,q_60,w_400,c_limit,fl_progressive/assets/images/10341699/2022/8/25/c23fd879-a9b3-4515-a181-558523a71b9b1661423122029-LOCOMOTIVE-Men-Black--Grey-Slim-Fit-Checked-Casual-Shirt-342-1.jpg",
    price:340,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "men",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Shirt4",
    image:"https://images-eu.ssl-images-amazon.com/images/I/81EqA--jXFL._AC._SR360,460.jpg",
    price:440,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Shirt5",
    image:"https://images-eu.ssl-images-amazon.com/images/I/81EqA--jXFL._AC._SR360,460.jpg",
    price:60,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Shirt6",
    image:"https://static-01.daraz.com.np/p/55a66637d60518d7dcea7808058c1fcb.jpg",
    price:70,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "women",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Shirt7",
    image:"https://contents.mediadecathlon.com/p1484240/ab565f3675dbdd7e3c486175e2c16583/p1484240.jpg",
    price:80,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["s", "m", "l"],
    agegroup: "children",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Shirt8",
    image:"https://images-eu.ssl-images-amazon.com/images/I/61KNBTw4K8S._AC._SR360,460.jpg",
    price:90,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "children",
    category: "Shirt",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },

  //   Jeans
  {
    cartItems:[],
    name: "Jeans1",
    image:"https://asset1.cxnmarksandspencer.com/is/image/mands/SD_03_T17_8452X_E2_X_EC_90",
    price:140,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Jeans2",
    image:"https://media.everlane.com/image/upload/c_scale,dpr_3.0,f_auto,q_auto,w_auto/c_limit,w_400/v1/i/22e84c5c_ec6e.jpg",
    price:240,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Jeans3",
    image:"https://media.wrangler.com/i/wrangler/6up-me-jeans-aug31-2022",
    price:340,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "men",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Jeans4",
    image:"https://cdn.shopify.com/s/files/1/0608/7874/9892/products/51BwBzrPk8-YTKN01BB008MidBlue_1_540x.jpg?v=1666693724",
    price:440,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Jeans5",
    image:"https://assets.ajio.com/medias/sys_master/root/h09/hcd/12085139111966/-1117Wx1400H-440794191-mediumblue-MODEL.jpg",
    price:60,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Jeans6",
    image:"https://thumbs.dreamstime.com/b/blue-jeans-10328995.jpg",
    price:70,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "women",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Jeans7",
    image:"https://media.gettyimages.com/id/173239968/photo/skinny-tight-blue-jeans-on-white-background.jpg?s=612x612&w=gi&k=20&c=QqoFe-m6N_FQKu6KyDVrHUwmKUyh3nkFK8QbDrl3OVM=",
    price:80,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["s", "m", "l"],
    agegroup: "children",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Jeans8",
    image:"https://assets.vogue.com/photos/6303e99aeccd2d497c480185/1:1/w_2667,h_2667,c_limit/slide_22.jpg",
    price:90,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "children",
    category: "Jeans",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },

  //   other
  {
    cartItems:[],
    name: "Other1",
    image:"https://i.pinimg.com/originals/dc/5b/7e/dc5b7ed8db06bcf15cf25a37c8bd62bc.jpg",
    price:140,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Other2",
    image:"https://static9.depositphotos.com/1013513/1169/i/950/depositphotos_11699738-stock-photo-variety-of-casual-shirts-on.jpg",
    price:240,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "men",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Other3",
    image:"https://img.freepik.com/free-vector/dirty-clothes-set-t-shirts-socks-with-mud-spots-pile-clothes-laundry-basket-clean-linen-isolated-flat-vector-illustrations-housekeeping-cleanliness-concept_74855-9854.jpg?w=2000",
    price:340,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "men",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Other4",
    image:"https://i.insider.com/5ccb2641021b4c42d41c8d2a?width=1000&format=jpeg&auto=webp",
    price:440,
    color: ["green", "red", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Other5",
    image:"https://content.jdmagicbox.com/comp/ahmednagar/d8/9999px241.x241.120629163407.t2d8/catalogue/rajendra-cloth-stores-sangamner-ahmednagar-readymade-garment-retailers-7w0ay.jpg",
    price:60,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "women",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Other6",
    image:"https://assets.designhill.com/resize_img.php?atyp=st_page_file&pth=ft_bt_thlcirlblirirb_org||BT5976||two_heading_left_content_image_right_link_button_left_image_right_info_right_button_right_image_img&flp=1568788430-1206740205d81cfce2b4423-60645169.png",
    price:70,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["l", "xl", "xxl"],
    agegroup: "women",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Other7",
    image:"https://st.depositphotos.com/1177973/1908/i/950/depositphotos_19086649-stock-photo-heap-of-cloth-fabrics-close.jpg",
    price:80,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["s", "m", "l"],
    agegroup: "children",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
  {
    cartItems:[],
    name: "Other8",
    image:"https://media.glamour.com/photos/607f2749febb5e66fe7c52cf/master/pass/terry%20cloth%20trend_jumpsuit.jpg",
    price:90,
    color: ["green", "yellow", "blue"],
    stock:400,
    size: ["m", "l", "xl"],
    agegroup: "children",
    category: "other",
    description:
      "So by colonel hearted ferrars. Draw from upon here gone add one. He in sportsman household otherwise it perceived instantly. Is inquiry no he several excited am. Called though excuse length ye needed it he having.",
  },
];

module.exports = product